// ================================================================
//  Command: /neural analyze (Neural Summary & Proactive Protection)
// ================================================================

import { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } from 'discord.js';
import { buildEmbed } from '../../../shared/utils/embedBuilder.js';
import config         from '../../../shared/config/config.js';

export default {
  data: new SlashCommandBuilder()
    .setName('neural')
    .setDescription('Access the Aura Neural Control Center')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
    .addSubcommand(s => s
      .setName('analyze')
      .setDescription('Generate a Neural Summary of the current channel vibe and safety')
    )
    .addSubcommand(s => s
      .setName('shield')
      .setDescription('Check the status of the Neural Protection system')
    ),

  async execute(client, interaction) {
    if (!interaction.guild) return;
    const sub = interaction.options.getSubcommand();

    await interaction.deferReply({ ephemeral: true });

    if (sub === 'analyze') {
      try {
        // 1. Fetch recent activity context
        const messages = await interaction.channel.messages.fetch({ limit: 50 });
        const contextString = messages
          .filter(m => !m.author.bot)
          .map(m => `${m.author.username}: ${m.content}`)
          .slice(0, 30)
          .join('\n');

        if (!contextString) {
          return interaction.editReply({ 
            embeds: [buildEmbed({ type: 'info', description: '📭 Not enough recent human activity to generate a neural summary.' })] 
          });
        }

        // 2. Query AI for 'Neural Summary'
        const prompt = `
          Analyze the following Discord chat logs and provide a "Neural Vibe Summary".
          Highlight:
          - The current mood/vibe (Calm, Chaotic, Helpful, etc.)
          - Any potential safety risks or toxic patterns.
          - Proactive suggestion for staff (e.g. "Suggest a slowmode", "Acknowledge helpful users").
          
          Respond in a professional, premium, holographic aesthetic tone.
          Chat Logs:
          ${contextString}
        `;

        if (!client.ai.isAvailable()) {
          return interaction.editReply({ 
            embeds: [buildEmbed({ type: 'error', description: '❌ Neural Core is offline (AI not configured).' })] 
          });
        }

        const result = await client.ai.prompt(prompt);

        return interaction.editReply({
          embeds: [buildEmbed({
            type: 'ai',
            title: '🧠 Neural Channel Analysis',
            author: `Aura Neural Intelligence • Channel: #${interaction.channel.name}`,
            description: result.content.slice(0, 4000),
            footer: 'This analysis is generated by AI observing pattern behaviors.',
            timestamp: true
          })]
        });
      } catch (err) {
        client.logger.error('[Aura Analyze] Error:', err);
        return interaction.editReply({ 
          embeds: [buildEmbed({ type: 'error', description: '❌ Failed to synchronize with the Neural Core.' })] 
        });
      }
    }

    if (sub === 'shield') {
      // Dummy status for "Proactive Protection" concepts
      const shieldStatus = {
        raidDetection: 'Active (Monitoring Joins)',
        toxicityScanners: 'Online',
        aiContextRetention: 'Healthy (24h Window)',
        neuralFirewall: 'Synchronized'
      };

      return interaction.editReply({
        embeds: [buildEmbed({
          type: 'success',
          title: '🛡️ Aura Neural Shield Status',
          description: 'The Proactive Protection system is monitoring server pulses.',
          fields: Object.entries(shieldStatus).map(([key, val]) => ({
            name: key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
            value: `\`${val}\``,
            inline: true
          })),
          footer: 'Aura v2.5 • Unified Core',
          timestamp: true
        })]
      });
    }
  }
};
